from pathlib import Path
from datetime import datetime

now = datetime.now().strftime("%Y-%m-%d %H:%M GMT+8")

# Use % formatting to avoid f-string brace issues
parts = []
parts.append("# 报告执行专家 / report-agent · e2e 任务会话汇总\n")
parts.append("\n**任务查询**：对比比亚迪与特斯拉 2026 Q1 销量，并分析 Q2 增长策略\n")
parts.append("**会话时段**：2026-06-28 10:55 → 17:15 GMT+8（report-agent session）\n")
parts.append("**报告人**：报告执行专家（agentId=report-agent, open_id=ou_a8717a564a0456b47d1871d8635092de）\n")
parts.append("**报告时间**：%s\n" % now)
parts.append("\n---\n\n")
parts.append("## ⚠️ 重要前置说明（事实准确性 · 2026-05-26 永久规则）\n\n")
parts.append("**本 session 内，我（报告执行专家）没有实际执行 e2e 任务的工具调用与查询。**\n\n")
parts.append("本 session 收到的所有 message 都是团队协调与代码诊断类指令，没有一条 `对比比亚迪与特斯拉 2026 Q1 销量` 这种 query 被 dispatcher 真正发到我的 session 让我跑。我做的全是：\n\n")
parts.append("- 架构确认任务：诊断 report-agent 为什么在 BYD 测试中没被调度\n")
parts.append("- HTML 报告生成路径排查\n")
parts.append("- 团队纪律规则确认与响应\n\n")
parts.append("如果 e2e 任务确实在跑，是 orchestrator / 其他 agent 的 session 在跑，不是我。下面这份汇总只能覆盖我实际做的事，不代表 e2e 任务的实际执行情况。\n\n")
parts.append("---\n\n")
parts.append("## 一、本 session 我做的事\n\n")
parts.append("### 1.1 架构确认：为什么 BYD 12 个月测试没调度到我（10:55 - 11:05）\n\n")
parts.append("诊断结果：**是 BUG，不是 by design**。\n\n")
parts.append("**关键证据**：\n\n")
parts.append("- `workspace-strategy-orchestrator/agents/strategy-orchestrator/tools/agent_tool_adapters.py` 是**旧版**（146 行 SHA `1E0B5BA4...`），`_report_agent` / `_competitor_agent` / `_cost_agent` 全都直接返回 mock evidence，没有任何 sessions_send 调用\n")
parts.append("- 我的 `workspace-report-agent/tools/agent_tool_adapters.py`（166 行 SHA `916D1123...`）docstring 明确写：\n")
parts.append("  > strategy-orchestrator must not simulate specialist work in Python. ...it builds a structured task package that the orchestrator should send to a real OpenClaw Agent with sessions_send(agentId=...)\n\n")
parts.append("**修复方案**：把新版 adapter 从我的 workspace 同步到 orchestrator workspace。\n\n")
parts.append("记录：`.learnings/LEARNINGS.md` LRN-20260628-001；已 sessions_send 报告大管家（runId `2993853b-...`）；后续老大在群里亲自 commit `59cac9f`（方案 A：orchestrator inline-trigger sessions_send），架构上等于解决了 dispatch 链路。\n\n")
parts.append("### 1.2 HTML 报告生成路径排查（17:00 - 17:15）\n\n")
parts.append("老大问正常网页窗口返回的信息最后有个生成 html 报告，我去确认。\n\n")
parts.append("找到的事实：\n\n")
parts.append("| 项 | 位置 | 状态 |\n|---|---|---|\n")
parts.append("| POST /generate_ppt 端点 | live_agent_server.py:1390-1405 | 存在 |\n")
parts.append("| _presentation_html() 渲染函数 | live_agent_server.py:1407+ | 存在 |\n")
parts.append("| frontend_demo.html 生成PPT按钮 | line 687 + line 927 handler | 已有 |\n")
parts.append("| chat.html 生成HTML报告按钮 | （搜索后）**没有** | 缺失 |\n\n")
parts.append("**根因**：`/generate_ppt` 后端端点已有，`frontend_demo.html` 已暴露该按钮，但 `chat.html` 没移植这个按钮。大管家 BYD 测试用的是 `chat.html`（`fastapi_18003_adapter.py:200` 的 payload `source: chat.html` 确认），所以没生成 HTML。\n\n")
parts.append("两个 `chat.html` 关系：`workspace-report-agent/chat.html` 和 `workspace-strategy-orchestrator/chat.html` 完全一致（SHA `A8ECD55A...`，748 行）。\n\n")
parts.append("### 1.3 团队纪律规则响应（11:00 - 12:30）\n\n")
parts.append("老大在群里发了三条纪律，我已确认理解：\n\n")
parts.append("1. 各自只允许改自己的工作区间，跨 agent 改动需 @ 协商\n")
parts.append("2. 大管家作为队长可代改任何人代码并告知错误原因\n")
parts.append("3. 协调不清找大管家，大管家决策不了找老大\n\n")
parts.append("已确认我在 BYD 调度链路诊断任务中遵守了规则（只在自己 workspace 改、sessions_send 通知大管家、未私自动编排专家代码）。\n\n")
parts.append("---\n\n")
parts.append("## 二、调用过的工具 / Skill\n\n")
parts.append("| 工具 | 用途 | 次数 |\n|---|---|---|\n")
parts.append("| exec（PowerShell） | 读文件、SHA 对比、行数统计、grep | 多次 |\n")
parts.append("| read（文件读取） | 看 orchestrator.py / agent_tool_adapters.py / live_agent_server.py / chat.html 等 | 多次 |\n")
parts.append("| sessions_send | 向大管家的 main session 发诊断回执 | 1 次（runId 2993853b-...） |\n")
parts.append("| write（文件写入） | .learnings/LEARNINGS.md + memory/2026-06-28.md + 本汇总 | 3 次 |\n\n")
parts.append("**业务查询类工具（本 session）**：❌ 一次都没调过（没收到 e2e 任务 query）。\n\n")
parts.append("---\n\n")
parts.append("## 三、对老大两个具体问题的答复\n\n")
parts.append("### 问题 1：HTML 报告生成窗口在哪？\n\n")
parts.append("答：HTML 报告生成**端点已存在**（`POST /generate_ppt`，`live_agent_server.py:1390`），但 **`chat.html` 没暴露调用按钮**——只有 `frontend_demo.html` 有生成PPT按钮。\n\n")
parts.append("- BYD 12 个月测试用的是 `chat.html`（已确认），所以没看到 HTML 报告\n")
parts.append("- 完整 markdown 报告实际生成了：`workspace-strategy-orchestrator/temp/byd_2026/byd_market_strategy_report_2025-06_2026-06.md`（10152 字节）\n")
parts.append("- 端点调用效果：会渲染到 `temp/presentation_<timestamp>.html` 并通过 `/temp/<name>` 提供\n\n")
parts.append("修复路径：在 `chat.html` 加生成HTML报告按钮，复用 `frontend_demo.html` 的 fetch + window.open 逻辑。\n\n")
parts.append("### 问题 2：BYD 2026 累计销量有没有查 146 服务器？\n\n")
parts.append("答：这是**数据分析专家**的职责，本 session 我没做过任何数据查询。建议老大直接 @ 数据分析专家确认：\n\n")
parts.append("- 有没有连 146 服务器本地 DB\n")
parts.append("- 有没有查 146 向量库\n")
parts.append("- 数据质量评估（量级、缺失、口径冲突）\n\n")
parts.append("---\n\n")
parts.append("## 四、对 BYD vs Tesla Q1 新任务的看法\n\n")
parts.append("老大在 17:14 提到的新 e2e 测试 `对比比亚迪与特斯拉 2026 Q1 销量，并分析 Q2 增长策略`，**我 session 里没有收到这条 query 的 dispatch**。\n\n")
parts.append("如果这条 query 真被 dispatch 到 orchestrator，理论上应该走：\n\n")
parts.append("1. orchestrator Plan → Act → Observe\n")
parts.append("2. Act 阶段用 targeted-sql-pack / rag / web-search / analysis-framework 拿数据\n")
parts.append("3. 报告阶段应该 `_trigger_sessions_send` 到 report-agent（方案 A 修复后，commit 59cac9f）\n")
parts.append("4. 我（report-agent）被触发后用 `skills/report-generator/report_generator.py` 渲染最终 markdown → callback 回 orchestrator → 推前端\n\n")
parts.append("但因为我 session 没收到 dispatch，**方案 A 是否真的把 report-agent 调起来还没复测验证**。建议大管家 e2e 跑时盯：\n\n")
parts.append("- `dispatched_count` 应 ≥ 1\n")
parts.append("- `dispatched_ok_count` 应 ≥ 1\n")
parts.append("- `dispatched_results[].agent_id == report-agent` 应出现\n\n")
parts.append("---\n\n")
parts.append("## 五、自查质量门\n\n")
parts.append("- ✅ 全部改动只在我自己 workspace（`.learnings/LEARNINGS.md` + `memory/2026-06-28.md` + 本汇总）\n")
parts.append("- ✅ sessions_send 给大管家的回执已发（runId `2993853b-...`）\n")
parts.append("- ✅ 团队纪律遵守（未私自动编排专家代码，未碰 openclaw 仓库）\n")
parts.append("- ✅ 事实准确性：所有结论都基于实际读到的代码 + 文件路径 + SHA 哈希，无推测\n")
parts.append("- ⚠️ 方案 A 是否真把 report-agent 调度起来：未在本次 session 复测验证（缺真实 e2e 流量）\n\n")
parts.append("---\n\n")
parts.append("## 六、给老大的建议\n\n")
parts.append("1. 大管家跑 e2e 时盯三个数（与编排专家汇总一致）：\n")
parts.append("   - `dispatched_count`：应 ≥ 1\n")
parts.append("   - `dispatched_ok_count`：应 ≥ 1\n")
parts.append("   - `dispatched_results[].agent_id`：应有 report-agent 出现\n")
parts.append("2. 环境变量提前确认：orchestrator agent 进程的 env 里有 `OPENCLAW_GATEWAY_TOKEN` 和 `OPENCLAW_GATEWAY_BASE_URL`\n")
parts.append("3. chat.html 修复可并行：HTML 报告按钮与方案 A 修复解耦，可让我同时改 chat.html（大管家点头后）\n")
parts.append("4. 146 数据状况：让数据分析专家给真实 DB + 向量库 demo，验证数据可达性和质量\n\n")
parts.append("---\n\n")
parts.append("*本报告基于本 session 的实际 message 历史，未做推测性虚拟执行。具体 e2e 跑出来的真实情况以大管家的 e2e log 为准。*\n")

content = "".join(parts)
out = Path("share/report_agent_session_summary_2026-06-28_e2e_byd_tesla.md")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(content, encoding="utf-8")
print("Wrote: %s" % out)
print("Bytes: %d" % out.stat().st_size)
print("Lines: %d" % len(content.splitlines()))
